(** THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS *)
(** [zebra_chain_arith] *)
Require Import Primitives.
Import Primitives.
Require Import Coq.ZArith.ZArith.
Require Import List.
Import ListNotations.
Local Open Scope Primitives_scope.
Module ZebraChainArith.

(** [core::convert::Infallible]
    Source: '/rustc/library/core/src/convert/mod.rs', lines 930:0-930:19
    Name pattern: [core::convert::Infallible]
    Visibility: public *)
Inductive core_convert_Infallible_t :=.

(** [core::ops::control_flow::ControlFlow]
    Source: '/rustc/library/core/src/ops/control_flow.rs', lines 89:0-89:31
    Name pattern: [core::ops::control_flow::ControlFlow]
    Visibility: public *)
Inductive core_ops_control_flow_ControlFlow_t (B : Type) (C : Type) :=
| Core_ops_control_flow_ControlFlow_Continue :
  C ->
  core_ops_control_flow_ControlFlow_t B C
| Core_ops_control_flow_ControlFlow_Break :
  B ->
  core_ops_control_flow_ControlFlow_t B C
.

Arguments Core_ops_control_flow_ControlFlow_Continue { _ } { _ }.
Arguments Core_ops_control_flow_ControlFlow_Break { _ } { _ }.

(** [core::ops::range::RangeFrom]
    Source: '/rustc/library/core/src/ops/range.rs', lines 197:0-197:25
    Name pattern: [core::ops::range::RangeFrom]
    Visibility: public *)
Record core_ops_range_RangeFrom_t (Idx : Type) :=
mkcore_ops_range_RangeFrom_t {
  core_ops_range_RangeFrom_start : Idx;
}
.

Arguments mkcore_ops_range_RangeFrom_t { _ }.
Arguments core_ops_range_RangeFrom_start { _ }.

(** [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public *)
Axiom core_option_Option_Insts_CoreOpsTry_traitTry_branch :
  forall{T : Type},
        option T -> result (core_ops_control_flow_ControlFlow_t (option
          core_convert_Infallible_t) T)
.

(** [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2793:4-2793:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public *)
Axiom
  core_option_Option_Insts_CoreOpsTry_traitFromResidualOptionInfallible_from_residual
  : forall(T : Type), option core_convert_Infallible_t -> result (option T)
.

(** Trait implementation: [core::slice::index::private_slice_index::{impl core::slice::index::private_slice_index::Sealed for core::ops::range::RangeFrom<usize>}]
    Source: '/rustc/library/core/src/slice/index.rs', lines 118:4-118:41
    Name pattern: [core::slice::index::private_slice_index::Sealed<core::ops::range::RangeFrom<usize>>] *)
Definition
  core_ops_range_RangeFromUsize_Insts_CoreSliceIndexPrivate_slice_indexSealed :
  core_slice_index_private_slice_index_Sealed (core_ops_range_RangeFrom_t
  usize) := mkcore_slice_index_private_slice_index_Sealed.

(** [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFrom<usize>}::index_mut]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 579:4-579:51
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>}::index_mut]
    Visibility: public *)
Axiom
  core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_index_mut
  :
  forall{T : Type},
        core_ops_range_RangeFrom_t usize -> slice T -> result ((slice T) *
          (slice T -> slice T))
.

(** [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFrom<usize>}::index]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 567:4-567:39
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>}::index]
    Visibility: public *)
Axiom
  core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_index
  :
  forall{T : Type},
        core_ops_range_RangeFrom_t usize -> slice T -> result (slice T)
.

(** [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFrom<usize>}::get_unchecked_mut]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 561:4-561:66
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>}::get_unchecked_mut]
    Visibility: public *)
Axiom
  core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_unchecked_mut
  :
  forall{T : Type},
        core_ops_range_RangeFrom_t usize -> mut_raw_ptr (slice T) -> result
          (mut_raw_ptr (slice T))
.

(** [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFrom<usize>}::get_unchecked]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 555:4-555:66
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>}::get_unchecked]
    Visibility: public *)
Axiom
  core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_unchecked
  :
  forall{T : Type},
        core_ops_range_RangeFrom_t usize -> const_raw_ptr (slice T) -> result
          (const_raw_ptr (slice T))
.

(** [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFrom<usize>}::get_mut]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 550:4-550:57
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>}::get_mut]
    Visibility: public *)
Axiom
  core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_mut
  :
  forall{T : Type},
        core_ops_range_RangeFrom_t usize -> slice T -> result ((option (slice
          T)) * (option (slice T) -> slice T))
.

(** [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFrom<usize>}::get]:
    Source: '/rustc/library/core/src/slice/index.rs', lines 545:4-545:45
    Name pattern: [core::slice::index::{core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>}::get]
    Visibility: public *)
Axiom
  core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get :
  forall{T : Type},
        core_ops_range_RangeFrom_t usize -> slice T -> result (option (slice
          T))
.

(** Trait implementation: [core::slice::index::{impl core::slice::index::SliceIndex<[T], [T]> for core::ops::range::RangeFrom<usize>}]
    Source: '/rustc/library/core/src/slice/index.rs', lines 541:0-541:62
    Name pattern: [core::slice::index::SliceIndex<core::ops::range::RangeFrom<usize>, [@T], [@T]>] *)
Definition
  core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice (T :
  Type) : core_slice_index_SliceIndex (core_ops_range_RangeFrom_t usize) (slice
  T) (slice T) := {|
  sealedInst :=
    core_ops_range_RangeFromUsize_Insts_CoreSliceIndexPrivate_slice_indexSealed;
  core_slice_index_SliceIndex_get :=
    core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get;
  core_slice_index_SliceIndex_get_mut :=
    core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_mut;
  core_slice_index_SliceIndex_get_unchecked :=
    core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_unchecked;
  core_slice_index_SliceIndex_get_unchecked_mut :=
    core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_get_unchecked_mut;
  core_slice_index_SliceIndex_index :=
    core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_index;
  core_slice_index_SliceIndex_index_mut :=
    core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice_index_mut;
|}.

(** [core::slice::{[T]}::is_empty]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 136:4-136:40
    Name pattern: [core::slice::{[@T]}::is_empty]
    Visibility: public *)
Axiom core_slice_Slice_is_empty : forall{T : Type}, slice T -> result bool.

(** [zebra_chain_arith::amount::COIN]
    Source: 'src/amount.rs', lines 4:0-4:34
    Visibility: public *)
Definition amount_COIN : i64 := 100000000%i64.

(** [zebra_chain_arith::amount::MAX_MONEY]
    Source: 'src/amount.rs', lines 7:0-7:45
    Visibility: public *)
Definition amount_MAX_MONEY : result i64 := i64_mul 21000000%i64 amount_COIN.

(** [zebra_chain_arith::amount::Constraint]
    Source: 'src/amount.rs', lines 11:0-15:1
    Visibility: public *)
Inductive amount_Constraint_t :=
| Amount_Constraint_NegativeAllowed : amount_Constraint_t
| Amount_Constraint_NonNegative : amount_Constraint_t
| Amount_Constraint_NegativeOrZero : amount_Constraint_t
.

(** [zebra_chain_arith::amount::{impl core::clone::Clone for zebra_chain_arith::amount::Constraint}::clone]:
    Source: 'src/amount.rs', lines 10:9-10:14
    Visibility: public *)
Definition amount_Constraint_Insts_CoreCloneClone_clone
  (self : amount_Constraint_t) : result amount_Constraint_t :=
  Ok self
.

(** Trait implementation: [zebra_chain_arith::amount::{impl core::clone::Clone for zebra_chain_arith::amount::Constraint}]
    Source: 'src/amount.rs', lines 10:9-10:14 *)
Definition amount_Constraint_Insts_CoreCloneClone : core_clone_Clone
  amount_Constraint_t := {|
  core_clone_Clone_clone := amount_Constraint_Insts_CoreCloneClone_clone;
|}.

(** Trait implementation: [zebra_chain_arith::amount::{impl core::marker::Copy for zebra_chain_arith::amount::Constraint}]
    Source: 'src/amount.rs', lines 10:16-10:20 *)
Definition amount_Constraint_Insts_CoreMarkerCopy : core_marker_Copy
  amount_Constraint_t := {|
  cloneInst := amount_Constraint_Insts_CoreCloneClone;
|}.

(** [zebra_chain_arith::amount::lo]:
    Source: 'src/amount.rs', lines 18:0-24:1
    Visibility: public *)
Definition amount_lo (c : amount_Constraint_t) : result i64 :=
  match c with
  | Amount_Constraint_NegativeAllowed => i <- amount_MAX_MONEY; i64_neg i
  | Amount_Constraint_NonNegative => Ok 0%i64
  | Amount_Constraint_NegativeOrZero => i <- amount_MAX_MONEY; i64_neg i
  end
.

(** [zebra_chain_arith::amount::hi]:
    Source: 'src/amount.rs', lines 27:0-33:1
    Visibility: public *)
Definition amount_hi (c : amount_Constraint_t) : result i64 :=
  match c with
  | Amount_Constraint_NegativeAllowed => amount_MAX_MONEY
  | Amount_Constraint_NonNegative => amount_MAX_MONEY
  | Amount_Constraint_NegativeOrZero => Ok 0%i64
  end
.

(** [zebra_chain_arith::amount::validate]:
    Source: 'src/amount.rs', lines 36:0-42:1
    Visibility: public *)
Definition amount_validate
  (c : amount_Constraint_t) (v : i64) : result (option i64) :=
  i <- amount_lo c;
  if i s<= v
  then (i1 <- amount_hi c; if v s<= i1 then Ok (Some v) else Ok None)
  else Ok None
.

(** [zebra_chain_arith::amount::checked_add]:
    Source: 'src/amount.rs', lines 45:0-48:1
    Visibility: public *)
Definition amount_checked_add
  (c : amount_Constraint_t) (a : i64) (b : i64) : result (option i64) :=
  let o := I64_checked_add a b in
  cf <- core_option_Option_Insts_CoreOpsTry_traitTry_branch o;
  match cf with
  | Core_ops_control_flow_ControlFlow_Continue val => amount_validate c val
  | Core_ops_control_flow_ControlFlow_Break residual =>
    core_option_Option_Insts_CoreOpsTry_traitFromResidualOptionInfallible_from_residual
      i64 residual
  end
.

(** [zebra_chain_arith::amount::checked_sub]:
    Source: 'src/amount.rs', lines 51:0-54:1
    Visibility: public *)
Definition amount_checked_sub
  (c : amount_Constraint_t) (a : i64) (b : i64) : result (option i64) :=
  let o := I64_checked_sub a b in
  cf <- core_option_Option_Insts_CoreOpsTry_traitTry_branch o;
  match cf with
  | Core_ops_control_flow_ControlFlow_Continue val => amount_validate c val
  | Core_ops_control_flow_ControlFlow_Break residual =>
    core_option_Option_Insts_CoreOpsTry_traitFromResidualOptionInfallible_from_residual
      i64 residual
  end
.

(** [zebra_chain_arith::amount::mul_u64]:
    Source: 'src/amount.rs', lines 57:0-63:1
    Visibility: public *)
Definition amount_mul_u64
  (c : amount_Constraint_t) (a : i64) (b : u64) : result (option i64) :=
  i <- scalar_cast I64 I128 a;
  i1 <- scalar_cast U64 I128 b;
  let o := I128_checked_mul i i1 in
  cf <- core_option_Option_Insts_CoreOpsTry_traitTry_branch o;
  match cf with
  | Core_ops_control_flow_ControlFlow_Continue val =>
    i2 <- scalar_cast I64 I128 core_num_I64_MIN;
    if val s< i2
    then Ok None
    else (
      i3 <- scalar_cast I64 I128 core_num_I64_MAX;
      if val s> i3
      then Ok None
      else (i4 <- scalar_cast I128 I64 val; amount_validate c i4))
  | Core_ops_control_flow_ControlFlow_Break residual =>
    core_option_Option_Insts_CoreOpsTry_traitFromResidualOptionInfallible_from_residual
      i64 residual
  end
.

(** [zebra_chain_arith::amount::div_u64]:
    Source: 'src/amount.rs', lines 66:0-72:1
    Visibility: public *)
Definition amount_div_u64
  (c : amount_Constraint_t) (a : i64) (b : u64) : result (option i64) :=
  if b s= 0%u64
  then Ok None
  else (
    i <- scalar_cast I64 I128 a;
    i1 <- scalar_cast U64 I128 b;
    q <- i128_div i i1;
    i2 <- scalar_cast I128 I64 q;
    amount_validate c i2)
.

(** [zebra_chain_arith::amount::neg]:
    Source: 'src/amount.rs', lines 75:0-77:1
    Visibility: public *)
Definition amount_neg (a : i64) : result i64 :=
  i64_neg a.

(** [zebra_chain_arith::compact_size::MAX_PROTOCOL_MESSAGE_LEN]
    Source: 'src/compact_size.rs', lines 9:0-9:58
    Visibility: public *)
Definition compact_size_MAX_PROTOCOL_MESSAGE_LEN : result u32 :=
  i <- u32_mul 2%u32 1024%u32; u32_mul i 1024%u32
.

(** [zebra_chain_arith::compact_size::encode]:
    Source: 'src/compact_size.rs', lines 12:0-38:1
    Visibility: public *)
Definition compact_size_encode (n : u64) : result (alloc_vec_Vec u8) :=
  if n s<= 252%u64
  then (i <- scalar_cast U64 U8 n; alloc_vec_Vec_push (alloc_vec_Vec_new u8) i)
  else
    if n s<= 65535%u64
    then (
      out <- alloc_vec_Vec_push (alloc_vec_Vec_new u8) 253%u8;
      let i := u64_and n 255%u64 in
      i1 <- scalar_cast U64 U8 i;
      out1 <- alloc_vec_Vec_push out i1;
      i2 <- u64_shr n 8%i32;
      let i3 := u64_and i2 255%u64 in
      i4 <- scalar_cast U64 U8 i3;
      alloc_vec_Vec_push out1 i4)
    else
      if n s<= 4294967295%u64
      then (
        out <- alloc_vec_Vec_push (alloc_vec_Vec_new u8) 254%u8;
        let i := u64_and n 255%u64 in
        i1 <- scalar_cast U64 U8 i;
        out1 <- alloc_vec_Vec_push out i1;
        i2 <- u64_shr n 8%i32;
        let i3 := u64_and i2 255%u64 in
        i4 <- scalar_cast U64 U8 i3;
        out2 <- alloc_vec_Vec_push out1 i4;
        i5 <- u64_shr n 16%i32;
        let i6 := u64_and i5 255%u64 in
        i7 <- scalar_cast U64 U8 i6;
        out3 <- alloc_vec_Vec_push out2 i7;
        i9 <- u64_shr n 24%i32;
        let i10 := u64_and i9 255%u64 in
        i11 <- scalar_cast U64 U8 i10;
        alloc_vec_Vec_push out3 i11)
      else (
        out <- alloc_vec_Vec_push (alloc_vec_Vec_new u8) 255%u8;
        let i := u64_and n 255%u64 in
        i1 <- scalar_cast U64 U8 i;
        out1 <- alloc_vec_Vec_push out i1;
        i2 <- u64_shr n 8%i32;
        let i3 := u64_and i2 255%u64 in
        i4 <- scalar_cast U64 U8 i3;
        out2 <- alloc_vec_Vec_push out1 i4;
        i5 <- u64_shr n 16%i32;
        let i6 := u64_and i5 255%u64 in
        i7 <- scalar_cast U64 U8 i6;
        out3 <- alloc_vec_Vec_push out2 i7;
        i9 <- u64_shr n 24%i32;
        let i10 := u64_and i9 255%u64 in
        i11 <- scalar_cast U64 U8 i10;
        out4 <- alloc_vec_Vec_push out3 i11;
        i12 <- u64_shr n 32%i32;
        let i13 := u64_and i12 255%u64 in
        i14 <- scalar_cast U64 U8 i13;
        out5 <- alloc_vec_Vec_push out4 i14;
        i15 <- u64_shr n 40%i32;
        let i17 := u64_and i15 255%u64 in
        i18 <- scalar_cast U64 U8 i17;
        out6 <- alloc_vec_Vec_push out5 i18;
        i19 <- u64_shr n 48%i32;
        let i20 := u64_and i19 255%u64 in
        i21 <- scalar_cast U64 U8 i20;
        out7 <- alloc_vec_Vec_push out6 i21;
        i22 <- u64_shr n 56%i32;
        let i23 := u64_and i22 255%u64 in
        i24 <- scalar_cast U64 U8 i23;
        alloc_vec_Vec_push out7 i24)
.

(** [zebra_chain_arith::compact_size::from_le2]:
    Source: 'src/compact_size.rs', lines 41:0-43:1
    Visibility: public *)
Definition compact_size_from_le2 (b0 : u8) (b1 : u8) : result u16 :=
  i <- scalar_cast U8 U16 b0;
  i1 <- scalar_cast U8 U16 b1;
  i2 <- u16_shl i1 8%i32;
  Ok (u16_or i i2)
.

(** [zebra_chain_arith::compact_size::from_le4]:
    Source: 'src/compact_size.rs', lines 46:0-48:1
    Visibility: public *)
Definition compact_size_from_le4
  (b0 : u8) (b1 : u8) (b2 : u8) (b3 : u8) : result u32 :=
  i <- scalar_cast U8 U32 b0;
  i1 <- scalar_cast U8 U32 b1;
  i2 <- u32_shl i1 8%i32;
  let i3 := u32_or i i2 in
  i4 <- scalar_cast U8 U32 b2;
  i5 <- u32_shl i4 16%i32;
  let i6 := u32_or i3 i5 in
  i7 <- scalar_cast U8 U32 b3;
  i9 <- u32_shl i7 24%i32;
  Ok (u32_or i6 i9)
.

(** [zebra_chain_arith::compact_size::from_le8]:
    Source: 'src/compact_size.rs', lines 51:0-57:1
    Visibility: public *)
Definition compact_size_from_le8
  (b0 : u8) (b1 : u8) (b2 : u8) (b3 : u8) (b4 : u8) (b5 : u8) (b6 : u8)
  (b7 : u8) :
  result u64
  :=
  i <- scalar_cast U8 U64 b0;
  i1 <- scalar_cast U8 U64 b1;
  i2 <- u64_shl i1 8%i32;
  let i3 := u64_or i i2 in
  i4 <- scalar_cast U8 U64 b2;
  i5 <- u64_shl i4 16%i32;
  let i6 := u64_or i3 i5 in
  i7 <- scalar_cast U8 U64 b3;
  i9 <- u64_shl i7 24%i32;
  let i10 := u64_or i6 i9 in
  i11 <- scalar_cast U8 U64 b4;
  i12 <- u64_shl i11 32%i32;
  let i13 := u64_or i10 i12 in
  i14 <- scalar_cast U8 U64 b5;
  i15 <- u64_shl i14 40%i32;
  let i17 := u64_or i13 i15 in
  i18 <- scalar_cast U8 U64 b6;
  i19 <- u64_shl i18 48%i32;
  let i20 := u64_or i17 i19 in
  i21 <- scalar_cast U8 U64 b7;
  i22 <- u64_shl i21 56%i32;
  Ok (u64_or i20 i22)
.

(** [zebra_chain_arith::compact_size::decode]:
    Source: 'src/compact_size.rs', lines 62:0-103:1
    Visibility: public *)
Definition compact_size_decode
  (bytes : slice u8) : result (option (u64 * (alloc_vec_Vec u8))) :=
  b <- core_slice_Slice_is_empty bytes;
  if b
  then Ok None
  else (
    b1 <- slice_index_usize bytes 0%usize;
    if b1 s<= 252%u8
    then (
      i <- scalar_cast U8 U64 b1;
      s <-
        core_slice_index_Slice_index
          (core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice
          u8) bytes {| core_ops_range_RangeFrom_start := 1%usize |};
      v <- alloc_slice_Slice_to_vec core_clone_CloneU8 s;
      Ok (Some (i, v)))
    else
      if b1 s= 253%u8
      then
        let i := slice_len bytes in
        if i s< 3%usize
        then Ok None
        else (
          i1 <- slice_index_usize bytes 1%usize;
          i2 <- slice_index_usize bytes 2%usize;
          n <- compact_size_from_le2 i1 i2;
          i3 <- scalar_cast U16 U64 n;
          if i3 s>= 253%u64
          then (
            s <-
              core_slice_index_Slice_index
                (core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice
                u8) bytes {| core_ops_range_RangeFrom_start := 3%usize |};
            v <- alloc_slice_Slice_to_vec core_clone_CloneU8 s;
            Ok (Some (i3, v)))
          else Ok None)
      else
        if b1 s= 254%u8
        then
          let i := slice_len bytes in
          if i s< 5%usize
          then Ok None
          else (
            i1 <- slice_index_usize bytes 1%usize;
            i2 <- slice_index_usize bytes 2%usize;
            i3 <- slice_index_usize bytes 3%usize;
            i4 <- slice_index_usize bytes 4%usize;
            n <- compact_size_from_le4 i1 i2 i3 i4;
            i5 <- scalar_cast U32 U64 n;
            if i5 s>= 65536%u64
            then (
              s <-
                core_slice_index_Slice_index
                  (core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice
                  u8) bytes {| core_ops_range_RangeFrom_start := 5%usize |};
              v <- alloc_slice_Slice_to_vec core_clone_CloneU8 s;
              Ok (Some (i5, v)))
            else Ok None)
        else
          let i := slice_len bytes in
          if i s< 9%usize
          then Ok None
          else (
            i1 <- slice_index_usize bytes 1%usize;
            i2 <- slice_index_usize bytes 2%usize;
            i3 <- slice_index_usize bytes 3%usize;
            i4 <- slice_index_usize bytes 4%usize;
            i5 <- slice_index_usize bytes 5%usize;
            i6 <- slice_index_usize bytes 6%usize;
            i7 <- slice_index_usize bytes 7%usize;
            i9 <- slice_index_usize bytes 8%usize;
            n <- compact_size_from_le8 i1 i2 i3 i4 i5 i6 i7 i9;
            if n s>= 4294967296%u64
            then (
              s <-
                core_slice_index_Slice_index
                  (core_ops_range_RangeFromUsize_Insts_CoreSliceIndexSliceIndexSliceSlice
                  u8) bytes {| core_ops_range_RangeFrom_start := 9%usize |};
              v <- alloc_slice_Slice_to_vec core_clone_CloneU8 s;
              Ok (Some (n, v)))
            else Ok None))
.

(** [zebra_chain_arith::compact_size::message_try_from]:
    Source: 'src/compact_size.rs', lines 106:0-112:1
    Visibility: public *)
Definition compact_size_message_try_from (n : u32) : result (option u32) :=
  i <- compact_size_MAX_PROTOCOL_MESSAGE_LEN;
  if n s<= i then Ok (Some n) else Ok None
.

(** [zebra_chain_arith::height::MAX_AS_U32]
    Source: 'src/height.rs', lines 4:0-4:41
    Visibility: public *)
Definition height_MAX_AS_U32 : result u32 := u32_div core_num_U32_MAX 2%u32.

(** [zebra_chain_arith::height::try_from_u32]:
    Source: 'src/height.rs', lines 7:0-13:1
    Visibility: public *)
Definition height_try_from_u32 (n : u32) : result (option u32) :=
  i <- height_MAX_AS_U32; if n s<= i then Ok (Some n) else Ok None
.

(** [zebra_chain_arith::height::add]:
    Source: 'src/height.rs', lines 17:0-25:1
    Visibility: public *)
Definition height_add (h : u32) (d : i64) : result (option u32) :=
  lhs <- scalar_cast U32 I64 h;
  let o := I64_checked_add lhs d in
  cf <- core_option_Option_Insts_CoreOpsTry_traitTry_branch o;
  match cf with
  | Core_ops_control_flow_ControlFlow_Continue val =>
    if val s< 0%i64
    then Ok None
    else (
      i <- height_MAX_AS_U32;
      i1 <- scalar_cast U32 I64 i;
      if val s> i1
      then Ok None
      else (i2 <- scalar_cast I64 U32 val; Ok (Some i2)))
  | Core_ops_control_flow_ControlFlow_Break residual =>
    core_option_Option_Insts_CoreOpsTry_traitFromResidualOptionInfallible_from_residual
      u32 residual
  end
.

(** [zebra_chain_arith::height::sub]:
    Source: 'src/height.rs', lines 28:0-36:1
    Visibility: public *)
Definition height_sub (h : u32) (d : i64) : result (option u32) :=
  lhs <- scalar_cast U32 I64 h;
  let o := I64_checked_sub lhs d in
  cf <- core_option_Option_Insts_CoreOpsTry_traitTry_branch o;
  match cf with
  | Core_ops_control_flow_ControlFlow_Continue val =>
    if val s< 0%i64
    then Ok None
    else (
      i <- height_MAX_AS_U32;
      i1 <- scalar_cast U32 I64 i;
      if val s> i1
      then Ok None
      else (i2 <- scalar_cast I64 U32 val; Ok (Some i2)))
  | Core_ops_control_flow_ControlFlow_Break residual =>
    core_option_Option_Insts_CoreOpsTry_traitFromResidualOptionInfallible_from_residual
      u32 residual
  end
.

(** [zebra_chain_arith::height::sub_h]:
    Source: 'src/height.rs', lines 39:0-41:1
    Visibility: public *)
Definition height_sub_h (lhs : u32) (rhs : u32) : result i64 :=
  i <- scalar_cast U32 I64 lhs; i1 <- scalar_cast U32 I64 rhs; i64_sub i i1
.

End ZebraChainArith.
