-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zebra_chain_arith]
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

/- You can remove the following line by using the CLI option `-all-computable`: -/
noncomputable section

namespace zebra_chain_arith

/-- [core::option::{impl core::ops::try_trait::Try for core::option::Option<T>}::branch]:
    Source: '/rustc/library/core/src/option.rs', lines 2779:4-2779:64
    Name pattern: [core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::Try<core::option::Option<@T>>}::branch"]
axiom core.option.Option.Insts.CoreOpsTry_traitTry.branch
  {T : Type} :
  Option T → Result (core.ops.control_flow.ControlFlow (Option
    core.convert.Infallible) T)

/-- [core::option::{impl core::ops::try_trait::FromResidual<core::option::Option<core::convert::Infallible>> for core::option::Option<T>}::from_residual]:
    Source: '/rustc/library/core/src/option.rs', lines 2793:4-2793:67
    Name pattern: [core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual]
    Visibility: public -/
@[rust_fun
  "core::option::{core::ops::try_trait::FromResidual<core::option::Option<@T>, core::option::Option<core::convert::Infallible>>}::from_residual"]
axiom
  core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
  (T : Type) : Option core.convert.Infallible → Result (Option T)

/-- [zebra_chain_arith::amount::COIN]
    Source: 'src/amount.rs', lines 4:0-4:34
    Visibility: public -/
@[global_simps, irreducible] def amount.COIN : Std.I64 := 100000000#i64

/-- [zebra_chain_arith::amount::MAX_MONEY]
    Source: 'src/amount.rs', lines 7:0-7:45
    Visibility: public -/
@[global_simps, irreducible]
def amount.MAX_MONEY : Result Std.I64 := 21000000#i64 * amount.COIN

/-- [zebra_chain_arith::amount::Constraint]
    Source: 'src/amount.rs', lines 11:0-15:1
    Visibility: public -/
@[discriminant isize]
inductive amount.Constraint where
| NegativeAllowed : amount.Constraint
| NonNegative : amount.Constraint
| NegativeOrZero : amount.Constraint

/-- [zebra_chain_arith::amount::{impl core::clone::Clone for zebra_chain_arith::amount::Constraint}::clone]:
    Source: 'src/amount.rs', lines 10:9-10:14
    Visibility: public -/
def amount.Constraint.Insts.CoreCloneClone.clone
  (self : amount.Constraint) : Result amount.Constraint := do
  ok self

/-- Trait implementation: [zebra_chain_arith::amount::{impl core::clone::Clone for zebra_chain_arith::amount::Constraint}]
    Source: 'src/amount.rs', lines 10:9-10:14 -/
@[reducible]
def amount.Constraint.Insts.CoreCloneClone : core.clone.Clone amount.Constraint
  := {
  clone := amount.Constraint.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [zebra_chain_arith::amount::{impl core::marker::Copy for zebra_chain_arith::amount::Constraint}]
    Source: 'src/amount.rs', lines 10:16-10:20 -/
@[reducible]
def amount.Constraint.Insts.CoreMarkerCopy : core.marker.Copy amount.Constraint
  := {
  cloneInst := amount.Constraint.Insts.CoreCloneClone
}

/-- [zebra_chain_arith::amount::lo]:
    Source: 'src/amount.rs', lines 18:0-24:1
    Visibility: public -/
def amount.lo (c : amount.Constraint) : Result Std.I64 := do
  match c with
  | amount.Constraint.NegativeAllowed => let i ← amount.MAX_MONEY
                                         -. i
  | amount.Constraint.NonNegative => ok 0#i64
  | amount.Constraint.NegativeOrZero => let i ← amount.MAX_MONEY
                                        -. i

/-- [zebra_chain_arith::amount::hi]:
    Source: 'src/amount.rs', lines 27:0-33:1
    Visibility: public -/
def amount.hi (c : amount.Constraint) : Result Std.I64 := do
  match c with
  | amount.Constraint.NegativeAllowed => amount.MAX_MONEY
  | amount.Constraint.NonNegative => amount.MAX_MONEY
  | amount.Constraint.NegativeOrZero => ok 0#i64

/-- [zebra_chain_arith::amount::validate]:
    Source: 'src/amount.rs', lines 36:0-42:1
    Visibility: public -/
def amount.validate
  (c : amount.Constraint) (v : Std.I64) : Result (Option Std.I64) := do
  let i ← amount.lo c
  if i <= v
  then let i1 ← amount.hi c
       if v <= i1
       then ok (some v)
       else ok none
  else ok none

/-- [zebra_chain_arith::amount::checked_add]:
    Source: 'src/amount.rs', lines 45:0-48:1
    Visibility: public -/
def amount.checked_add
  (c : amount.Constraint) (a : Std.I64) (b : Std.I64) :
  Result (Option Std.I64)
  := do
  let o ← lift (I64.checked_add a b)
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val => amount.validate c val
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      Std.I64 residual

/-- [zebra_chain_arith::amount::checked_sub]:
    Source: 'src/amount.rs', lines 51:0-54:1
    Visibility: public -/
def amount.checked_sub
  (c : amount.Constraint) (a : Std.I64) (b : Std.I64) :
  Result (Option Std.I64)
  := do
  let o ← lift (I64.checked_sub a b)
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val => amount.validate c val
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      Std.I64 residual

/-- [zebra_chain_arith::amount::mul_u64]:
    Source: 'src/amount.rs', lines 57:0-63:1
    Visibility: public -/
def amount.mul_u64
  (c : amount.Constraint) (a : Std.I64) (b : Std.U64) :
  Result (Option Std.I64)
  := do
  let i ← lift (IScalar.cast .I128 a)
  let i1 ← lift (UScalar.hcast .I128 b)
  let o ← lift (I128.checked_mul i i1)
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    let i2 ← lift (IScalar.cast .I128 core.num.I64.MIN)
    if val < i2
    then ok none
    else
      let i3 ← lift (IScalar.cast .I128 core.num.I64.MAX)
      if val > i3
      then ok none
      else let i4 ← lift (IScalar.cast .I64 val)
           amount.validate c i4
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      Std.I64 residual

/-- [zebra_chain_arith::amount::div_u64]:
    Source: 'src/amount.rs', lines 66:0-72:1
    Visibility: public -/
def amount.div_u64
  (c : amount.Constraint) (a : Std.I64) (b : Std.U64) :
  Result (Option Std.I64)
  := do
  if b = 0#u64
  then ok none
  else
    let i ← lift (IScalar.cast .I128 a)
    let i1 ← lift (UScalar.hcast .I128 b)
    let q ← i / i1
    let i2 ← lift (IScalar.cast .I64 q)
    amount.validate c i2

/-- [zebra_chain_arith::amount::neg]:
    Source: 'src/amount.rs', lines 75:0-77:1
    Visibility: public -/
def amount.neg (a : Std.I64) : Result Std.I64 := do
  -. a

/-- [zebra_chain_arith::compact_size::MAX_PROTOCOL_MESSAGE_LEN]
    Source: 'src/compact_size.rs', lines 9:0-9:58
    Visibility: public -/
@[global_simps, irreducible]
def compact_size.MAX_PROTOCOL_MESSAGE_LEN : Result Std.U32 := do
  let i ← 2#u32 * 1024#u32
  i * 1024#u32

/-- [zebra_chain_arith::compact_size::encode]:
    Source: 'src/compact_size.rs', lines 12:0-38:1
    Visibility: public -/
def compact_size.encode (n : Std.U64) : Result (alloc.vec.Vec Std.U8) := do
  if n <= 252#u64
  then
    let i ← lift (UScalar.cast .U8 n)
    alloc.vec.Vec.push (alloc.vec.Vec.new Std.U8) i
  else
    if n <= 65535#u64
    then
      let out ← alloc.vec.Vec.push (alloc.vec.Vec.new Std.U8) 253#u8
      let i ← lift (n &&& 255#u64)
      let i1 ← lift (UScalar.cast .U8 i)
      let out1 ← alloc.vec.Vec.push out i1
      let i2 ← n >>> 8#i32
      let i3 ← lift (i2 &&& 255#u64)
      let i4 ← lift (UScalar.cast .U8 i3)
      alloc.vec.Vec.push out1 i4
    else
      if n <= 4294967295#u64
      then
        let out ← alloc.vec.Vec.push (alloc.vec.Vec.new Std.U8) 254#u8
        let i ← lift (n &&& 255#u64)
        let i1 ← lift (UScalar.cast .U8 i)
        let out1 ← alloc.vec.Vec.push out i1
        let i2 ← n >>> 8#i32
        let i3 ← lift (i2 &&& 255#u64)
        let i4 ← lift (UScalar.cast .U8 i3)
        let out2 ← alloc.vec.Vec.push out1 i4
        let i5 ← n >>> 16#i32
        let i6 ← lift (i5 &&& 255#u64)
        let i7 ← lift (UScalar.cast .U8 i6)
        let out3 ← alloc.vec.Vec.push out2 i7
        let i8 ← n >>> 24#i32
        let i9 ← lift (i8 &&& 255#u64)
        let i10 ← lift (UScalar.cast .U8 i9)
        alloc.vec.Vec.push out3 i10
      else
        let out ← alloc.vec.Vec.push (alloc.vec.Vec.new Std.U8) 255#u8
        let i ← lift (n &&& 255#u64)
        let i1 ← lift (UScalar.cast .U8 i)
        let out1 ← alloc.vec.Vec.push out i1
        let i2 ← n >>> 8#i32
        let i3 ← lift (i2 &&& 255#u64)
        let i4 ← lift (UScalar.cast .U8 i3)
        let out2 ← alloc.vec.Vec.push out1 i4
        let i5 ← n >>> 16#i32
        let i6 ← lift (i5 &&& 255#u64)
        let i7 ← lift (UScalar.cast .U8 i6)
        let out3 ← alloc.vec.Vec.push out2 i7
        let i8 ← n >>> 24#i32
        let i9 ← lift (i8 &&& 255#u64)
        let i10 ← lift (UScalar.cast .U8 i9)
        let out4 ← alloc.vec.Vec.push out3 i10
        let i11 ← n >>> 32#i32
        let i12 ← lift (i11 &&& 255#u64)
        let i13 ← lift (UScalar.cast .U8 i12)
        let out5 ← alloc.vec.Vec.push out4 i13
        let i14 ← n >>> 40#i32
        let i15 ← lift (i14 &&& 255#u64)
        let i16 ← lift (UScalar.cast .U8 i15)
        let out6 ← alloc.vec.Vec.push out5 i16
        let i17 ← n >>> 48#i32
        let i18 ← lift (i17 &&& 255#u64)
        let i19 ← lift (UScalar.cast .U8 i18)
        let out7 ← alloc.vec.Vec.push out6 i19
        let i20 ← n >>> 56#i32
        let i21 ← lift (i20 &&& 255#u64)
        let i22 ← lift (UScalar.cast .U8 i21)
        alloc.vec.Vec.push out7 i22

/-- [zebra_chain_arith::compact_size::from_le2]:
    Source: 'src/compact_size.rs', lines 41:0-43:1
    Visibility: public -/
def compact_size.from_le2 (b0 : Std.U8) (b1 : Std.U8) : Result Std.U16 := do
  let i ← lift (UScalar.cast .U16 b0)
  let i1 ← lift (UScalar.cast .U16 b1)
  let i2 ← i1 <<< 8#i32
  ok (i ||| i2)

/-- [zebra_chain_arith::compact_size::from_le4]:
    Source: 'src/compact_size.rs', lines 46:0-48:1
    Visibility: public -/
def compact_size.from_le4
  (b0 : Std.U8) (b1 : Std.U8) (b2 : Std.U8) (b3 : Std.U8) :
  Result Std.U32
  := do
  let i ← lift (UScalar.cast .U32 b0)
  let i1 ← lift (UScalar.cast .U32 b1)
  let i2 ← i1 <<< 8#i32
  let i3 ← lift (i ||| i2)
  let i4 ← lift (UScalar.cast .U32 b2)
  let i5 ← i4 <<< 16#i32
  let i6 ← lift (i3 ||| i5)
  let i7 ← lift (UScalar.cast .U32 b3)
  let i8 ← i7 <<< 24#i32
  ok (i6 ||| i8)

/-- [zebra_chain_arith::compact_size::from_le8]:
    Source: 'src/compact_size.rs', lines 51:0-57:1
    Visibility: public -/
def compact_size.from_le8
  (b0 : Std.U8) (b1 : Std.U8) (b2 : Std.U8) (b3 : Std.U8) (b4 : Std.U8)
  (b5 : Std.U8) (b6 : Std.U8) (b7 : Std.U8) :
  Result Std.U64
  := do
  let i ← lift (UScalar.cast .U64 b0)
  let i1 ← lift (UScalar.cast .U64 b1)
  let i2 ← i1 <<< 8#i32
  let i3 ← lift (i ||| i2)
  let i4 ← lift (UScalar.cast .U64 b2)
  let i5 ← i4 <<< 16#i32
  let i6 ← lift (i3 ||| i5)
  let i7 ← lift (UScalar.cast .U64 b3)
  let i8 ← i7 <<< 24#i32
  let i9 ← lift (i6 ||| i8)
  let i10 ← lift (UScalar.cast .U64 b4)
  let i11 ← i10 <<< 32#i32
  let i12 ← lift (i9 ||| i11)
  let i13 ← lift (UScalar.cast .U64 b5)
  let i14 ← i13 <<< 40#i32
  let i15 ← lift (i12 ||| i14)
  let i16 ← lift (UScalar.cast .U64 b6)
  let i17 ← i16 <<< 48#i32
  let i18 ← lift (i15 ||| i17)
  let i19 ← lift (UScalar.cast .U64 b7)
  let i20 ← i19 <<< 56#i32
  ok (i18 ||| i20)

/-- [zebra_chain_arith::compact_size::decode]:
    Source: 'src/compact_size.rs', lines 62:0-103:1
    Visibility: public -/
def compact_size.decode
  (bytes : Slice Std.U8) :
  Result (Option (Std.U64 × (alloc.vec.Vec Std.U8)))
  := do
  let b ← core.slice.Slice.is_empty bytes
  if b
  then ok none
  else
    let b1 ← Slice.index_usize bytes 0#usize
    if b1 <= 252#u8
    then
      let i ← lift (UScalar.cast .U64 b1)
      let s ←
        core.slice.index.Slice.index
          (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8) bytes
          { start := 1#usize }
      let v ← alloc.slice.Slice.to_vec core.clone.CloneU8 s
      ok (some (i, v))
    else
      if b1 = 253#u8
      then
        let i := Slice.len bytes
        if i < 3#usize
        then ok none
        else
          let i1 ← Slice.index_usize bytes 1#usize
          let i2 ← Slice.index_usize bytes 2#usize
          let n ← compact_size.from_le2 i1 i2
          let i3 ← lift (UScalar.cast .U64 n)
          if i3 >= 253#u64
          then
            let i4 ← lift (UScalar.cast .U64 n)
            let s ←
              core.slice.index.Slice.index
                (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8) bytes
                { start := 3#usize }
            let v ← alloc.slice.Slice.to_vec core.clone.CloneU8 s
            ok (some (i4, v))
          else ok none
      else
        if b1 = 254#u8
        then
          let i := Slice.len bytes
          if i < 5#usize
          then ok none
          else
            let i1 ← Slice.index_usize bytes 1#usize
            let i2 ← Slice.index_usize bytes 2#usize
            let i3 ← Slice.index_usize bytes 3#usize
            let i4 ← Slice.index_usize bytes 4#usize
            let n ← compact_size.from_le4 i1 i2 i3 i4
            let i5 ← lift (UScalar.cast .U64 n)
            if i5 >= 65536#u64
            then
              let i6 ← lift (UScalar.cast .U64 n)
              let s ←
                core.slice.index.Slice.index
                  (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8) bytes
                  { start := 5#usize }
              let v ← alloc.slice.Slice.to_vec core.clone.CloneU8 s
              ok (some (i6, v))
            else ok none
        else
          let i := Slice.len bytes
          if i < 9#usize
          then ok none
          else
            let i1 ← Slice.index_usize bytes 1#usize
            let i2 ← Slice.index_usize bytes 2#usize
            let i3 ← Slice.index_usize bytes 3#usize
            let i4 ← Slice.index_usize bytes 4#usize
            let i5 ← Slice.index_usize bytes 5#usize
            let i6 ← Slice.index_usize bytes 6#usize
            let i7 ← Slice.index_usize bytes 7#usize
            let i8 ← Slice.index_usize bytes 8#usize
            let n ← compact_size.from_le8 i1 i2 i3 i4 i5 i6 i7 i8
            if n >= 4294967296#u64
            then
              let s ←
                core.slice.index.Slice.index
                  (core.slice.index.SliceIndexRangeFromUsizeSlice Std.U8) bytes
                  { start := 9#usize }
              let v ← alloc.slice.Slice.to_vec core.clone.CloneU8 s
              ok (some (n, v))
            else ok none

/-- [zebra_chain_arith::compact_size::message_try_from]:
    Source: 'src/compact_size.rs', lines 106:0-112:1
    Visibility: public -/
def compact_size.message_try_from (n : Std.U32) : Result (Option Std.U32) := do
  let i ← compact_size.MAX_PROTOCOL_MESSAGE_LEN
  if n <= i
  then ok (some n)
  else ok none

/-- [zebra_chain_arith::height::MAX_AS_U32]
    Source: 'src/height.rs', lines 4:0-4:41
    Visibility: public -/
@[global_simps, irreducible]
def height.MAX_AS_U32 : Result Std.U32 := core.num.U32.MAX / 2#u32

/-- [zebra_chain_arith::height::try_from_u32]:
    Source: 'src/height.rs', lines 7:0-13:1
    Visibility: public -/
def height.try_from_u32 (n : Std.U32) : Result (Option Std.U32) := do
  let i ← height.MAX_AS_U32
  if n <= i
  then ok (some n)
  else ok none

/-- [zebra_chain_arith::height::add]:
    Source: 'src/height.rs', lines 17:0-25:1
    Visibility: public -/
def height.add (h : Std.U32) (d : Std.I64) : Result (Option Std.U32) := do
  let lhs ← lift (UScalar.hcast .I64 h)
  let o ← lift (I64.checked_add lhs d)
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    if val < 0#i64
    then ok none
    else
      let i ← height.MAX_AS_U32
      let i1 ← lift (UScalar.hcast .I64 i)
      if val > i1
      then ok none
      else let i2 ← lift (IScalar.hcast .U32 val)
           ok (some i2)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      Std.U32 residual

/-- [zebra_chain_arith::height::sub]:
    Source: 'src/height.rs', lines 28:0-36:1
    Visibility: public -/
def height.sub (h : Std.U32) (d : Std.I64) : Result (Option Std.U32) := do
  let lhs ← lift (UScalar.hcast .I64 h)
  let o ← lift (I64.checked_sub lhs d)
  let cf ← core.option.Option.Insts.CoreOpsTry_traitTry.branch o
  match cf with
  | core.ops.control_flow.ControlFlow.Continue val =>
    if val < 0#i64
    then ok none
    else
      let i ← height.MAX_AS_U32
      let i1 ← lift (UScalar.hcast .I64 i)
      if val > i1
      then ok none
      else let i2 ← lift (IScalar.hcast .U32 val)
           ok (some i2)
  | core.ops.control_flow.ControlFlow.Break residual =>
    core.option.Option.Insts.CoreOpsTry_traitFromResidualOptionInfallible.from_residual
      Std.U32 residual

/-- [zebra_chain_arith::height::sub_h]:
    Source: 'src/height.rs', lines 39:0-41:1
    Visibility: public -/
def height.sub_h (lhs : Std.U32) (rhs : Std.U32) : Result Std.I64 := do
  let i ← lift (UScalar.hcast .I64 lhs)
  let i1 ← lift (UScalar.hcast .I64 rhs)
  i - i1

end zebra_chain_arith
