-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [zebra_chain_arith]: type definitions
import Aeneas
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace zebra_chain_arith

/-- [zebra_chain_arith::amount::Constraint]
    Source: 'src/amount.rs', lines 11:0-15:1
    Visibility: public -/
@[discriminant isize]
inductive amount.Constraint where
| NegativeAllowed : amount.Constraint
| NonNegative : amount.Constraint
| NegativeOrZero : amount.Constraint

end zebra_chain_arith
